### ISSUE TITLE
Software Keyboard doesn't show on newer Android versions

### ISSUE THREAD

**Issue by Abestanis** [Abestanis/APython#22]
> Sorry, I thought you were referring to an issue in your Python editor project. Can you please open a new issue with some more information, like the Android and Python version and whether or not you installed the readline module.
> 
> I'll close this issue once I have more time to actually get back to this project, maybe towards the end of this year.

Im on Android 11, I dont know why but once terminal opens, i cant put any text
![image](https://user-images.githubusercontent.com/72782632/160287732-71b0850c-950e-4281-91d2-c632bd5897bc.png)
Only stuff i see :(, not able to put any text

_Originally posted by @m-anshuman2166 in https://github.com/Abestanis/APython/issues/21#issuecomment-1079949172_

**Comment by Abestanis** [comment]
@m-anshuman2166 I can verify in an Android emulator that the software keyboard doesn't show up. I will investigate.
In the meantime, downloading the `readline` module will cause the software keyboard to activate and it also allows for a much better editing experience.

**Comment by m-anshuman2166** [comment]
Thanks for getting back into this!

**Comment by Abestanis** [comment]
Let me know if the latest version shows the keyboard for you.
